### PR TITLE
explain how to call sigal from git, se #284

### PR DESCRIPTION
**Pull request by anarcat**

### CODE REVIEW

**Comment by saimn** [comment]
Thanks @anarcat , looks useful, but I think this deserves its own section. The current section is for a local rebuild, and with your method it is a build on a remote server. So maybe something like "How to build automatically the gallery on a remote server" ?

**Comment by anarcat** [comment]
okay, makes sense, i'll rephrase

**Comment by anarcat** [comment]
done

**Comment by saimn** [comment]
Thanks!

**Pull request merged**
