### PR TITLE
Galleria template with image title and GPS position

### PR DESCRIPTION
**Pull request by cbosdo**
These changes are some small improvements on the galleria template. The one moving title infos to the layer is only a matter of taste.

The UserComment exif data is not the best defined thing in the world... we can face some weird values depending on the image editor.

### CODE REVIEW

**Comment by cbosdo** [comment]
@saimn I just fixed a race between galleria and map events and switched from openlayer 2 to leafletjs. It has the advantage to be much more scalable: I am loading 200+ pictures in the same folder without any trouble.

I also dropped the first commit as you introduced something similar in between. I hope it'll be OK for you this time ;)

**Comment by saimn** [comment]
Thanks for the update Cedric, it is great to see that you are still working on this ;).
I don't have a lot of time for sigal currently, but I will test this asap.

**Comment by muggenhor** [comment]
As an example of how this can look like: http://sigal-test-parque.mortis.eu/

I did modify two things though, first of all the URL text in the image description for the location info. I.e. to make it look like Nxx.xxxxxx, Ey.yyyyyy instead.

Secondly I added a keybind for map toggling (keycode 0x4D, aka 'm') because as you can see with this the map/picture toggling icon/button is displayed *above* the album listing (if there are sub albums), which makes switching a great deal more difficult. For usability it's probably better to place it directly below or above the gallery display itself. Also the same toggling icon is not displayed for the gallery root if that has pictures. That should probably be fixed as well.

Other than that this is great :+1:.

PS I'll probably remove

**Comment by cbosdo** [comment]
@muggenhor you probably have a patch to propose for this enhancement, right?

**Comment by muggenhor** [comment]
@cbosdo only hacks in the template file, here's a diff below.

I did a few more things there though, one of which you probably don't want to include in this pull (i.e. the `#fullscreen` stuff). All of my changes:

 * Move map-toggling icon to be just above the gallery.
 * Don't put the toggling icon in a table, use a `<div>` instead
 * Use 'anchored' coordinate descriptions (anchored to N/S and E/W) and make it a clickable link to OSM
 * Use https links for OSM
 * Make fullscreen switching possible, this you probably don't want, so ignore the CSS addition of `#fullscreen`, the addition of the `data-big` attribute to images, addition of the `fullscreen` link, addition of the `toggleFullscreen` keybind and event handler for the `fullscreen` link.

If I have the time and think of it I can clean this up in the weekend to be a separate commit on top of your branch, I definitely don't have the time right now though.

```diff
diff --git a/sigal/themes/galleria/templates/index.html b/sigal/themes/galleria/templates/index.html
index 48e851c..80b9372 100644
--- a/sigal/themes/galleria/templates/index.html
+++ b/sigal/themes/galleria/templates/index.html
@@ -42,6 +42,17 @@
         .galleria-thumbnails .galleria-image {
            opacity: 0.6;
         }
+        .icons {
+          float: right;
+        }
+        #gallery {
+          clear: both;
+        }
+        {% if settings.show_map and album.show_map %}
+        #fullscreen {
+          cursor: pointer;
+        }
+        {% endif %}
     </style>
     {% endif %}
   </head>
@@ -62,20 +73,10 @@
 
         {% if album.breadcrumb %}
         <h2>
-          <table>
-            <td>
           {%- for url, title in album.breadcrumb -%}
           <a href="{{ url }}">{{ title }}</a>
           {%- if not loop.last %} » {% endif -%}
           {% endfor -%}
-            </td>
-            <td style="width: 100%"></td>
-            <td>
-          {% if settings.show_map and album.show_map %}
-            <a class="gallery-map-toggle"><img src="{{ theme.url }}/img/map.png"/></a>
-          {% endif %}
-            </td>
-          </table>
         </h2>
         <hr>
         {% endif %}
@@ -108,21 +109,29 @@
               {% if media.exif.exposure %}Exposure: {{ media.exif.exposure }}, {% endif %}
               {% if media.exif.fstop %}Fstop: {{ media.exif.fstop }}{% endif %}
               {% if media.exif.gps %}
-                <br/>Location: {{ media.exif.gps.lat }}, {{ media.exif.gps.lon }}
-                <a href='http://www.openstreetmap.org/?mlat={{ media.exif.gps.lat }}&mlon={{ media.exif.gps.lon }}&zoom=12&layers=M' target='_blank' class='map'/>
+                <br/>Location: <a href='https://www.openstreetmap.org/?mlat={{
+                media.exif.gps.lat }}&amp;mlon={{ media.exif.gps.lon}}&amp;zoom=12&amp;layers=M' target='_blank' class='map'
+                >{{ 'N{:.6f}'.format(media.exif.gps.lat) if media.exif.gps.lat > 0 else 'S{:.6f}'.format(-media.exif.gps.lat) }}
+                 {{ 'E{:.6f}'.format(media.exif.gps.lon) if media.exif.gps.lon > 0 else 'W{:.6f}'.format(-media.exif.gps.lon) }}</a>
               {% endif %}
               {% if media.exif.datetime %}
                 <br>Date: {{ media.exif.datetime }}
               {% endif %}
             {% endif %}
           {%- endmacro %}
+        {% if settings.show_map and album.show_map %}
+        <div class="icons">
+          <a class="gallery-map-toggle"><img src="{{ theme.url }}/img/map.png"/></a>
+        </div>
+        {% endif %}
         <div id="gallery">
           {% for media in album.medias %}
             {% if media.type == "image" %}
               <a href="{{ media.filename }}">
                 <img src="{{ media.thumbnail }}" alt="{{ media.filename }}"
                     data-title="{{ media.title if media.title else media.filename }}"
-                    data-description="{{ img_description(media) }}"/>
+                    data-description="{{ img_description(media) }}"
+                   {% if media.big %} data-big="{{ media.big }}"{% endif %} />
               </a>
             {% endif %}
             {% if media.type == "video" %}
@@ -137,6 +146,7 @@
             {% endif %}
           {% endfor %}
         </div>
+        <a id="fullscreen">fullscreen</a>
         {% endif %}
 
         {% if album.zip %}
@@ -213,8 +223,8 @@
         if ($("#galleria-map").length == 0) {
             stage.after("<div id='galleria-map'></div>");
             map = L.map('galleria-map');
-            var attrib = '&copy; <a href="http://osm.org/copyright" title="OpenStreetMap" target="_blank">OpenStreetMap</a> contributors | Tiles Courtesy of <a href="http://www.mapquest.com/" title="MapQuest" target="_blank">MapQuest</a> <img src="http://developer.mapquest.com/content/osm/mq_logo.png" width="16" height="16">';
-            L.tileLayer('http://{s}.mqcdn.com/tiles/1.0.0/map/{z}/{x}/{y}.png', {
+            var attrib = '&copy; <a href="https://osm.org/copyright" title="OpenStreetMap" target="_blank">OpenStreetMap</a> contributors | Tiles Courtesy of <a href="https://www.mapquest.com/" title="MapQuest" target="_blank">MapQuest</a> <img src="https://developer.mapquest.com/content/osm/mq_logo.png" width="16" height="16">';
+            L.tileLayer('https://{s}-s.mqcdn.com/tiles/1.0.0/map/{z}/{x}/{y}.png', {
                         attribution: attrib,
                         subdomains: ['otile1','otile2','otile3','otile4']
                         }).addTo( map );
@@ -252,25 +262,8 @@
     });
     Galleria.run("#gallery");
 
-    Galleria.ready(function() {
-        this.attachKeyboard({
-            right: this.next,
-            left: this.prev
-         });
-
-        {% if settings.show_map and album.show_map %}
-        this.bind('loadfinish', function(e) {
-            init_map();
-            if (selected != e.index) {
-                selectMarker(features[e.index]);
-                selected = e.index;
-            }
-        });
-        {% endif %}
-     });
-
     {% if settings.show_map and album.show_map %}
-    $(".gallery-map-toggle").click(function() {
+    function galleryMapToggle() {
         /* Make sure the map is loaded */
         init_map();
 
@@ -293,8 +286,34 @@
             /* Change display of the Map link */
             $(".gallery-map-toggle img")[0].src = "{{ theme.url }}/img/photo.png";
         }
-    });
+    }
+    $(".gallery-map-toggle").click(galleryMapToggle);
     {% endif %}
+
+    Galleria.ready(function() {
+        this.attachKeyboard({
+            right: this.next,
+            left: this.prev,
+            0x46: this.toggleFullscreen,
+            {% if settings.show_map and album.show_map %}
+            0x4D: galleryMapToggle,
+            {% endif %}
+         });
+       var gallery = this;
+       $('#fullscreen').click(function() {
+          gallery.toggleFullscreen();
+        });
+
+        {% if settings.show_map and album.show_map %}
+        this.bind('loadfinish', function(e) {
+            init_map();
+            if (selected != e.index) {
+                selectMarker(features[e.index]);
+                selected = e.index;
+            }
+        });
+        {% endif %}
+     });
     </script>
     {% endif %}
     {% include 'analytics.html' %}
```

**Comment by muggenhor** [comment]
The changes as a branch: muggenhor/sigal@c314bd9bbf362f30351a1466cf163fbd4d68bd45
Feel free to pull them into your branch (which'll update this pull request)

**Comment by saimn** [comment]
I made a little test, and it works fine, really nice !
If you can have a look at @muggenhor 's changes; I hope we can finally integrate this in sigal !
@muggenhor : it seem you have some patch to use galleria in full screen mode ? It would be great if you could share this (and make a PR) when you have some time.

**Comment by muggenhor** [comment]
@saimn yes, I've got a patch for fullscreen mode. It was set up a bit hacky though, so I've cleaned it up and pushed it to #149.

**Comment by muggenhor** [comment]
It seems there's a problem when you have a gallery with mixed photos. Specifically a few with and a few without GPS Exif data. If, for example you have 3 photos, 1 has GPS data, 2 doesn't and 3 does, then when selecting the second dot on the map the second photo is activated instead of the third. I.e. the mapping of the position-marking-dots to the photo-indices appears to depend on the assumption that there are just as much photos in the gallery and that they appear in the same order: this is a wrong assumption.

**Comment by saimn** [comment]
Hi @cbosdo and @muggenhor , any chance that one of you could help to get this merged for the mext release ? It would ne nice to finally have it.

**Comment by cbosdo** [comment]
Sorry for the delay, that project is kind of low priority to me and get less attention that it should have.
Got @muggenhor changes in + fixed the bug he mentioned in his last comment.

**Comment by cbosdo** [comment]
Fixed some rebase errors, now all green for merge

**Comment by saimn** [comment]
Merged, finally ;), thanks Cédric !

**Pull request merged**
