### PR TITLE
Implement album sorting

### PR DESCRIPTION
**Pull request by trapperhoney**
This adds an 'albums_sort_attr' configuration modeled off of the
'medias_sort_attr'.  It defaults to the existing behavior of sorting
sub-albums by directory name.  It allows sort by any metadata attribute
stored in the album metadata file.

The existing album sort test wasn't really verifying album sorting
behavior, so I just re-wrote the whole thing to include tests for the
old behavior and new.

This should resolve issue #121

### CODE REVIEW

**Comment by saimn** [comment]
Looks good, thanks @trapperhoney !
Could you remove the `.index.md.swp` file and add yourself to the AUTHORS file ?

**Comment by trapperhoney** [comment]
Woops, sorry I missed the tmp file :\  I'd rather not include my name in the distributed source.  Is the github trail not good enough?

**Comment by saimn** [comment]
It can be your github pseudonym if you prefer, no problem with this.

**Comment by saimn** [comment]
Thanks !

**Comment by trapperhoney** [comment]
Thank you!

**Comment by tohojo** [comment]
How is this supposed to work? I tried adding an 'Order' field to index.md of each of my subdirectories and setting that as album_sort_attr. However, I just get an AttributeError when trying to build the gallery.

I ended up adding this to _get_metadata() of the Album class, but that's obviously not a workable solution to have to do that for all the interesting fields:

        try:
            self.order = self.meta['order'][0]
        except KeyError:
            self.order = self.settings.get('order')

**Comment by saimn** [comment]
@tohojo - Indeed, you're right, it works only with attributes of the Album objects ... Copying all the `meta` items as object attributes seems not a good option, so maybe we could allow some special syntax for albums_sort_attr, something like ` 'albums_sort_attr': ('meta', 'Order') ` ?

**Comment by tohojo** [comment]
Ah, good, so it wasn't just me who was missing something! :)

Yeah, having a way to specify meta fields would be good (thought that was what it was meant for). Maybe just falling back to looking in the metadata object if the attribute is not found on the Album object itself? That would avoid introducing new syntax... Not sure if there are field names that would clash in surprising ways, though?

**Comment by saimn** [comment]
> Maybe just falling back to looking in the metadata object if the attribute is not found on the Album object itself? That would avoid introducing new syntax..

Yep, that's another possibility. Maybe both could be allowed to resolve potential conflicts.

**Comment by tohojo** [comment]
Ah yes, that's a possibility. Can take a shot at a patch tomorrow. Any preferences on the syntax? Was thinking using 'meta.fieldname' could work?

**Comment by trapperhoney** [comment]
For what it's worth, the same (lack of metadata support) semantics apply to the sorting behavior of individual items and the items_sort_attr configuration option.

**Comment by saimn** [comment]
@tohojo - Great ! No string preference, `meta.fieldname` can work too.
@trapperhoney - Yes, good point. The media objects have more useful attributes, but their metadata is not accessible for the sort.

**Comment by tohojo** [comment]
Created #202 :)

**Pull request merged**
