### PR TITLE
Avoid black thumbnails with fade-in videos

### PR DESCRIPTION
**Pull request by jdn06**

### CODE REVIEW

**Comment by saimn** [comment]
Hi @jdn06 ,
this could be useful indeed, but Travis is failing and after a quick look it is because the test video's duration is ~2 seconds and you use 2 seconds for the `-ss` parameter ...
I'm not sure what's the best option here:
- extract duration from ffmpeg's output and check if it is > 2s
- add a setting to customize the `ss` vaue.

**Comment by jdn06** [comment]
I chose to add a parameter with a default value of 0. As everybody doesn't have the same kind of fade-in, it seems more useful than a check of the length of the video.

**Comment by saimn** [comment]
Thanks, but the tests still fails, could you check why ?

**Comment by saimn** [comment]
Great, thanks !

**Pull request merged**
