### PR TITLE
add a theme using photoswipe (http://photoswipe.com/).

### PR DESCRIPTION
**Pull request by franek**
This PR is linked to https://github.com/saimn/sigal/pull/164

Photoswipe library needs image size to render image (see http://photoswipe.com/documentation/faq.html). So, I have to add a specific property to return image size (disclaimer : I am a python beginner). We can't use 'img_size' property because depending on image orientation, image size can differ.

The first image is highlighted for each album.

Pictures are lazy loaded thanks to echo (https://github.com/toddmotto/echo).

TODO
======
- [x] improve CSS and HTML
- [x] improve responsive design
- [ ] add support for video (not supported)
- [x] add support for albums
- [x] add links
- [x] update documentation

### CODE REVIEW

**Comment by saimn** [comment]
It is really great to see a new theme coming to sigal, thanks @franek! I will try it soon.

**Comment by franek** [comment]
Thanks it is a basic theme. I am not a designer. It answers to my need. This theme depends on this PR https://github.com/saimn/sigal/pull/164

**Comment by iemejia** [comment]
since the dependent PR #164 is already merged, are there any plans to merge this soon ?

**Comment by franek** [comment]
@iemejia I have rebased the PR but there is still work on html/css (responsive design). I don't know if I will have time to work on it in the next days. Do not hesitate to propose improvement :p

**Comment by saimn** [comment]
It looks already good ! A few suggestions to improve the design (at least for me ;)) :
- put the album-list and breadcrumb divs in the content div, so that these get aligned with the text below
- remove the white border below the album-list

**Comment by franek** [comment]
@saimn I have applied what you have suggested. There are still some little things to do (video, links).

**Comment by franek** [comment]
At the moment, Photoswipe does not support video. Is possible to release this theme without video support ?!?

**Comment by saimn** [comment]
> At the moment, Photoswipe does not support video. Is possible to release this theme without video support ?!?

Yes, if you can just mention this in the docs, then it is not a problem for me.

**Comment by franek** [comment]
> Yes, if you can just mention this in the docs, then it is not a problem for me.

done. Thx

**Comment by lukecyca** [comment]
This is a wonderful contribution. Thank you @franek!

I have used this new theme for a gallery I've posted: http://lukeandmichelle.ca/cycamatic/

I did some work to improve the alignment of the thumbnails and to ensure the layout is responsive to small screens. I posted my changes [here](https://github.com/lukecyca/sigal/commit/bedec99df49b84b33847e0fb848faa689c25d942). If they're a useful addition to this PR, I can submit a PR to this branch so that they are amalgamated.

I tested these changes on Mac Chrome, Firefox, Safari, and Mobile Safari on iPhone 4S, and simulated a few other mobile devices using Chrome Devtools.

**Comment by franek** [comment]
Hi @lukecyca,

Nice. Seems very good. You can submit a PR to this branch and I will check.

Thx,

**Comment by franek** [comment]
thanks @lukecyca, I have merged your contribution and fix an alignment problem for menu.

@saimn If you are OK with this theme, you can merge this PR. thanks.

**Comment by saimn** [comment]
Merged ! Thanks for your work on this, I guess it is time to bump a new version :)

**Comment by franek** [comment]
\o/
I wanted to fix image path for photoswipe theme but you did it (see https://github.com/saimn/sigal/commit/1639154801f606e63c0c142c24d826a51488f47f). Thx

**Comment by iemejia** [comment]
New version, new version, yeeesss please, pypi !

**Pull request merged**
